apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../base/monitoring
patches:
  - path: monitoring-values.yaml
    target:
      kind: HelmRelease
      name: prometheus-stack
