apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "69.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-stack
        namespace: monitoring
      interval: 12h
  values:
    alertmanager:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-dev
        hosts:
        - alertmanager.example.com
        pathType: ImplementationSpecific
        tls:
        - secretName: alertmanager-tls
          hosts:
          - alertmanager.example.com

    grafana:
      adminUser: admin
      adminPassword: prom-operator
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-dev
        hosts:
        - monitoring.example.com
        tls:
        - secretName: monitoring-tls
          hosts:
          - monitoring.example.com
      sidecar:
        datasources:
          enabled: false
          defaultDatasourceEnabled: false
          isDefaultDatasource: false

    prometheus:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-dev
        hosts:
        - prometheus.example.com
        pathType: ImplementationSpecific
        tls:
        - secretName: prometheus-tls
          hosts:
          - prometheus.example.com
