apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metabase
  namespace: metabase
spec:
  interval: 30m
  chart:
    spec:
      chart: metabase
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: metabase
        namespace: metabase
      interval: 12h
  values:
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 6
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
    
    image:
      repository: metabase/metabase
      tag: latest

    database:
      type: postgres
      host: db-host
      port: db-port
      dbname: db-name
      username: db-username
      password: db-password

    ingress:
      hosts: 
      - metabase.example.com
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      path: /
      pathType: Prefix
      tls:
      - secretName: metabase-tls
        hosts:
        - metabase.example.com