##one per secret. This is better suited at the apps level

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: example         # whichever namespace your app lives in
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: db-credentials     # K8s Secret name that gets created
    creationPolicy: Owner
  data:
    - secretKey: password    # key inside the K8s Secret
      remoteRef:
        key: my-app/db-password  # name in AWS Secrets Manager