apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-cd
  namespace: argocd
spec:
  interval: 30m
  chart:
    spec:
      chart: argo-cd
      version: "7.x"
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: argocd
      interval: 12h
  values:
    global:
      domain: argocd.example.com
    server:
      name: argocd-server
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-dev
        ingressClassName: "nginx"
        hostname: "argocd.example.com"
        path: /
        pathType: Prefix
        tls: true